// Generado por web_i18n/i18n_rebuild.js (eu) a partir de web/js/epocas_fichas.js. No editar a mano: editar la memoria tm/eu.json y regenerar.
const EPOCAS_FICHAS = {
 "ant": {
  "anos": "K.a. VI. mendetik K.o. V. mendera arte (hitzarmenez, Erroma erori zen arte, 476an).",
  "abre": "<p>Joniako Greziar hirietan, Mileton adibidez, hainbat pentsalari natura jainkoengana jo gabe azaltzen hasten dira: <strong>mitotik logosera</strong> egiten den urratsa da. Herodotoren arabera, Talesek eguzki-eklipse bat iragarri zuen (K.a. 585ekoa). Lagungarri izan ziren merkataritza, Egiptorekin eta Babiloniarekin izandako harremana, alfabetozko idazkera eta apaiz-kasta batek jakintza kontrolatzen ez zuen hiriak.</p>",
  "social": "<p>Bizitza <strong>polisaren</strong>, hiri-estatuaren, inguruan antolatzen da. Bertan jaiotako gizon libreak bakarrik dira hiritar: emakumeak, bertan bizi diren atzerritarrak (metekoak) eta esklaboak kanpoan geratzen dira. Pentsatzeko aisialdia (<em>scholé</em>, «eskola» hitza handik dator) neurri handi batean esklaboen lanean oinarritzen da. Haurrak Homeroren poemekin hezten dira, eta K.a. V. mendean sofistek publikoki hitz egiten irakasteagatik kobratzen hasten dira.</p>\n<p>Alexandroren ondoren, jakintzaren gunea <strong>Alexandriara</strong> aldatzen da, bere Museoarekin eta Liburutegiarekin (K.a. III. mendea), eta geroago Erromara, non Greziako filosofia elitean hezkuntzaren parte bihurtzen den.</p>",
  "politico": "<p>Polisak independenteak dira eta sarritan aurkariak. Atenasek <strong>demokrazia</strong> garatzen du Klistenesen erreformen ondoren (K.a. 508), persiarrak garaitzen ditu Gerra Medikoetan (K.a. 490-479) eta Peloponesoko gerra galtzen du Espartaren aurka (K.a. 431-404); handik gutxira Sokrates heriotzara kondenatzen du (K.a. 399).</p>\n<p>Alexandro Handiak inperio erraldoia sortzen du (K.a. 336-323), erresuma helenistikoetan banatzen dena, eta horiek <strong>Erromak</strong> xurgatzen ditu, errepublika gisa eta gero inperio gisa (K.a. 27tik aurrera). 380an kristautasuna Inperioko erlijio ofizial bihurtzen da, eta 476an Mendebaldeko Erromatar Inperioa erortzen da.</p>",
  "ciencia": "<p>Greziarrek Egiptoko eta Babiloniako kalkulu-teknikak <strong>matematika frogatzaile</strong> bihurtzen dituzte: pitagorikoak eta, K.a. 300 inguruan, Euklidesen <em>Elementuak</em>. Eratostenesek Lurraren zirkunferentzia kalkulatzen du (K.a. III. mendea); Aristarkok Lurra Eguzkiaren inguruan biratzen dela proposatzen du, baina Lurra erdian jartzen duen eredua nagusituko da, Ptolomeok K.o. II. mendean sistematizatu zuena. Hipokratesen medikuntzak gaixotasunen kausa naturalak bilatzen ditu, eta Aristotelesek biologia sortzen du animaliak behatuz.</p>\n<p>Teknikak, ordea, aurrerapen txikia egiten du: esklaboen lan ugariarekin, ia ez dago makinen bidez ahalegina aurrezteko interesik.</p>",
  "pensamiento": "<ul>\n<li><strong>Aurresokratikoak:</strong> <em>arkhe</em> bilatzen dute, naturaren (<em>physis</em>) printzipioa: ura, airea, zenbakiak, atomoak.</li>\n<li><strong>Gizakiarenganako buelta:</strong> sofistek legeak naturalak ala konbentzionalak diren eztabaidatzen dute, eta Sokratesek justizia eta bertutea zer diren galdetzen du.</li>\n<li><strong>Sistema handiak:</strong> Platonek (Ideiak) eta Aristotelesek (gauzen baitako forma) jakintza guztiak antolatzen dituzte.</li>\n<li><strong>Eskola helenistikoak:</strong> zinikoek, epikurearrek, estoikoek eta eszeptikoek, batez ere, mundu ziurgabe batean lasaitasunez nola bizi galdetzen diote beren buruari.</li>\n<li><strong>Garaiaren amaiera:</strong> Plotinoren neoplatonismoa eta kristautasunarekiko topaketa. Tertulianok galdetu zuen zer zerikusi zuten Atenasek eta Jerusalemek; beste batzuek, Agustinek bezala, Greziako filosofia aliatu bihurtuko dute.</li>\n</ul>",
  "rupturas": "<p>Antzinako filosofia ez da desagertzen: kristautasunak xurgatu eta eraldatu egiten du. Agustin Hiponakoak fedea platondar begiekin irakurtzen du. 529an Justiniano enperadoreak paganoei Atenasen filosofia irakastea debekatzen die, eta Greziako jakintza, batez ere, Bizantzion bizirik jarraitzen du eta, VIII. mendetik aurrera, mundu islamiarrean, non Aristoteles arabierara itzultzen eta mendeetan zehar iruzkintzen den.</p>",
  "trampa": "<p>«Greziarrek filosofia ezerezetik asmatu zuten.» Egipton eta Babilonian edan zuten, eta ez ziren bakarrak: mende berberetan Buda irakasten ari zen Indian eta Konfuzio Txinan. Greziarren berezitasuna eztabaida arrazional eta publikoa metodo bihurtzea izan zen. Eta beste tranpa bat: antzinako filosofia ez da Platon eta Aristoteles bakarrik, ia hamabi mendetako eskola desberdinak baizik.</p>"
 },
 "med": {
  "anos": "V. mendetik XV. mendera arte (mintegiaren ardatzean, 476tik 1492ra).",
  "abre": "<p>476an Mendebaldeko Erromatar Inperioa erortzen da. Hirien hondamendiaren erdian, <strong>Eliza</strong> idazkera, liburuak eta irakaskuntza gordetzen dituen erakunde bihurtzen da. Agustin Hiponakoak, 430ean hiltzen denak bere hiria bandaloek setiatzen zuten bitartean, Greziako filosofiaren eta kristau fedearen arteko sintesi handia idatzita uzten du, hurrengo mendeak gidatuko dituena.</p>",
  "social": "<p>Gizarte <strong>estamentala</strong> da: 1000. urte inguruan otoitz egiten zutenek, borrokatzen zutenek eta lan egiten zutenek osatzen zutela deskribatzen zen. Gehiengoa landan bizi da, jaun baten mendean (<strong>feudalismoa</strong>). Monastegiek antzinako liburuak kopiatu eta gordetzen dituzte; komentuak, halaber, emakumeek ikasi eta idatz zezaketen leku urrietako bat dira, Hildegarda Bingenekoa kasu.</p>\n<p>XI. mendetik aurrera hiriak eta merkataritza berpizten dira, eta <strong>unibertsitateak</strong> sortzen dira (Bolonia, Paris, Oxford, Salamanca). Izurri Beltzak (1347-1351) Europako biztanleriaren zati handi bat hiltzen du, agian herena.</p>",
  "politico": "<p>Erromaren ondoren erresuma germaniarrak sortzen dira; Karlomagno enperadore koroatzen dute 800. urtean. Ekialdean <strong>Bizantziar Inperioak</strong> jarraitzen du, eta VII. mendetik islama Arabiatik Iberiar penintsulara hedatzen da (al-Andalus, 711tik). Aita santuek eta enperadoreek mendeetan zehar eztabaidatzen dute zeinek duen azken hitza, eta gurutzadek (1096-1291) kristauak eta musulmanak aurrez aurre jartzen dituzte.</p>\n<p>Garaia bi dataz ixten da: Konstantinopla otomandarren eskuetan erortzea (1453) eta, 1492an, Granada hartzea eta Kolon Amerikara iristea.</p>",
  "ciencia": "<p>VIII.-X. mendeetako <strong>Bagdaden</strong> Aristoteles, Euklides, Ptolomeo eta Galeno arabierara itzultzen dira. Al-Khwarizmik izena ematen die <strong>aljebrari</strong> eta algoritmoari; Avizenak <em>Medikuntzaren Kanona</em> idazten du, Europan mendeetan zehar ikasia. XII. eta XIII. mendeetan, Toledon eta beste leku batzuetan, jakintza hori latinera itzultzen da, eta Europak zenbaki indo-arabiarrak eta zeroa hartzen ditu.</p>\n<p>Teknikak uste baino gehiago egiten du aurrera: golde astuna, errotak, erloju mekanikoa eta, 1450 inguruan, Gutenbergen mugitzeko moldeko <strong>inprenta</strong>.</p>",
  "pensamiento": "<ul>\n<li><strong>Fedea eta arrazoia:</strong> garaiaren arazo handia da sinesten dena frogatzen denarekin nola uztartu.</li>\n<li><strong>Patristika:</strong> Elizaren Aitek, Agustin buru dutela, fedea tresna platondarrekin pentsatzen dute.</li>\n<li><strong>Eskolastika:</strong> eskoletan eta unibertsitateetan metodo zorrotz batekin arrazoitzen da (irakurketa, auzia, disputa). Anselmok bere argudio ontologikoa proposatzen du; Tomas Akinokoak Aristoteles fedearekin harmonizatzen du.</li>\n<li><strong>Arabierazko eta hebreerazko filosofia:</strong> Avizenak, Averroesek eta Maimonidesek arazo berberak pentsatzen dituzte islametik eta judaismotik.</li>\n<li><strong>Unibertsalak:</strong> «gizakia» existitzen al da gizaki bakoitzaz gain? Abelardok eta Ockhamek izenak edo kontzeptuak direla erantzuten dute.</li>\n</ul>",
  "rupturas": "<p>XIV. mendean Ockhamek fedea arrazoitik bereizten du: sinesten dena ezin da frogatu, eta bere izena daraman labanak behar ez diren entitateak mozten ditu. Izurriak, Mendebaldeko Zismak (1378-1417), aldi berean bi eta hiru aita santu izan zituenak, eta humanista italiarrek eskolastikari egindako kritikak Errenazimenduari bidea irekitzen diote. Inprentak gainerakoa egingo du.</p>",
  "trampa": "<p>«Erdi Aroa garai ilun bat izan zen.» Izena humanistek asmatu zuten mespretxatzeko, baina bertan sortu ziren unibertsitateak, logikak maila oso altua lortu zuen eta antzinako jakintzaren erdia itzuli zen. Eta ez: Erdi Aroko jakintsuek ez zuten uste Lurra laua zenik; bere forma esferikoa unibertsitateetan irakasten zen, adibidez Sacroboscoren <em>Esferari buruzko tratatua</em> liburuaren bidez (XIII. mendea).</p>"
 },
 "ren": {
  "anos": "XV. mendearen erdialdetik XVI. mendearen amaierara arte (mintegiaren ardatzean, 1492tik 1600era).",
  "abre": "<p>Hiru berrikuntzak mundua aldatzen dute urte gutxitan: <strong>inprenta</strong> (1450 inguruan), liburuak ugaltzen dituena; Bizantziotik Italiara greziar jakintsuak eta eskuizkribuak iristea; eta Kolon Amerikara iristea (1492), antzinakoek ezagutzen zuten mundua zati bat baino ez zela erakusten duena.</p>",
  "social": "<p>Italiako hiriak, Florentzia edo Venezia adibidez, merkataritzarekin eta bankuekin aberasten dira, eta Mediciak bezalako familiek artistei eta jakintsuei ordaintzen diete (<strong>mezenasgoa</strong>). Inprimatutako liburuak jende gehiagorengana iristen dira, eta idazteaz, irakasteaz edo printzeei aholku emateaz bizi den humanistaren irudia agertzen da.</p>\n<p>Amerikaren konkistak gizarte osoak suntsitzen ditu eta pertsona esklabo bihurtuen Atlantikoko merkataritza irekitzen du. Eztabaida filosofiko bat ere eragiten du: Valladolideko Batzarrean (1550-1551), Bartolome de las Casasek eta Juan Gines de Sepulvedak herri indigenak mendean hartu daitezkeen eztabaidatzen dute.</p>",
  "politico": "<p><strong>Estatu modernoak</strong> eratzen dira, boterea kontzentratzen duten erregeekin (Errege Katolikoak, Frantzia, Ingalaterra). Italia, estatu txikitan banatuta, potentzia handien guduleku da: testuinguru horretan idazten du Maquiavelok <em>Printzea</em> (1513).</p>\n<p>1517an Luterok bere 95 tesiak argitaratzen ditu eta protestanteen <strong>Erreforma</strong> hasten da. Europa erlijio aldetik banatzen da: erlijio-gerrak, Augsburgoko Bakea (1555), printze bakoitzari bere menekoen erlijioa aukeratzen uzten diona, eta Trentoko Kontzilioaren erantzun katolikoa (1545-1563).</p>",
  "ciencia": "<p>1543an bi liburu erabakigarri agertzen dira: Kopernikusen <em>Zeruko esferen iraultzei buruz</em>, Eguzkia erdian jartzen duena, eta Vesalioren anatomia, disekzioetan oinarrituta Galeno zuzentzen duena. Leonardo da Vincik artea, behaketa eta ingeniaritza uztartzen ditu. <strong>Iraultza zientifikoa</strong> hemen hasten da, eta XVII. mendean gailurrera iritsiko da, Kepler, Galileo, Harvey eta Newtonekin.</p>",
  "pensamiento": "<ul>\n<li><strong>Humanismoa:</strong> testu klasikoetara itzultzea jatorrizko hizkuntzan, eta gizakiaren duintasunean konfiantza, bere burua egiteko gai dela (Pico della Mirandola, <em>Gizakiaren duintasunari buruzko diskurtsoa</em>, 1486).</li>\n<li><strong>Kritika eta tolerantzia:</strong> Erasmok bere garaiko gehiegikeriez trufatzen da <em>Eromenaren laudorioa</em> lanean (1511) eta barne-erlijio baketsu bat defendatzen du.</li>\n<li><strong>Utopiak:</strong> Tomas Morok (<em>Utopia</em>, 1516) eta, geroago, Campanellak gizarte justuak irudikatzen dituzte benetakoak kritikatzeko.</li>\n<li><strong>Errealismo politikoa:</strong> Maquiavelok politika moral erlijiosotik bereizten du.</li>\n<li><strong>Natura infinitu bat:</strong> Nikolas Kusakoak eta Giordano Brunok, Inkisizioak 1600ean erre zuenak, mugarik gabeko unibertso bat pentsatzen dute.</li>\n</ul>",
  "rupturas": "<p>XVI. mendearen amaieran Elizaren autoritatea banatuta dago eta Aristotelesena zalantzan. Montaignek ia dena zalantzan jartzen du. Modernitateak herentzian jasotzen duen galdera da ezagutzarako oinarri segurua non aurkitu: Francis Baconek esperientzian oinarritutako metodo bat proposatzen du (<em>Novum organum</em>, 1620) eta Descartesek, arrazoian (<em>Metodoaren diskurtsoa</em>, 1637).</p>\n<p>«Ospetsuak» atalean Descartes garai honetan agertzen da, mintegiaren ardatzak 1600ean ixten duelako eta berak 1596an jaio zelako; baina bere lanak filosofia modernoa irekitzen du.</p>",
  "trampa": "<p>«Errenazimenduan zientziak erlijioa garaitu zuen.» Kopernikus Elizako kanonigoa zen, eta Kepler eta Galileo sinestunak ziren. Gainera, zientzia berriarekin batera magia, astrologia eta alkimia loratu ziren, humanista askok oso serio hartzen zituztenak.</p>"
 },
 "mod": {
  "anos": "XVII. mendea (mintegiaren ardatzean, filosofia modernoa 1600etik 1800era doa; Ilustrazioak bere fitxa propioa du hemen).",
  "abre": "<p><strong>Iraultza zientifikoak</strong> ezagutzeko modua aldatzen du. Galileok teleskopioa zerurantz zuzentzen du (1610) eta naturaren liburua matematikaren hizkuntzan idatzita dagoela defendatzen du (<em>Saiatzailea</em>, 1623). Antzinakoen autoritatea krisian dagoela, Descartesek hutsetik hasi nahi du, zalantzan jar ezin daitekeen egia batetik (<em>Metodoaren diskurtsoa</em>, 1637).</p>",
  "social": "<p>Krisi-mendea da: <strong>Hogeita Hamar Urteko Gerrak</strong> (1618-1648) Europa erdialdea suntsitzen du, eta epidemiak eta uzta txarrak ohikoak dira. Herbehereek, merkataritza-errepublika eta nahiko tolerantea denak, jazarritako edo deserosoak ziren pentsalariak hartzen dituzte: han bizi izan ziren Descartes eta Spinoza, bere komunitate judutarrak 1656an kanporatu zuena.</p>\n<p>Jakintsuek «letren errepublika» osatzen dute, Europa osoan elkarri gutunak idazten dizkiotena, Descartesenak eta Bohemiako Isabelenak bezala, eta lehen <strong>akademia zientifikoak</strong> sortzen dira: Londresko Royal Society (1660) eta Parisko Zientzia Akademia (1666).</p>",
  "politico": "<p><strong>Absolutismoa</strong> nagusitzen da: erregeak botere guztia kontzentratzen du, Luis XIV.ak Frantzian bezala (1643tik 1715era erreinatu zuen). Westfaliako Bakeak (1648) Europa estatu subiranotan antolatzen du. Ingalaterra salbuespena da: gerra zibil bat (1642-1651) Karlos I.a erregea 1649an exekutatuz amaitzen da, eta Iraultza Loriatsuak (1688-1689) koroaren boterea mugatzen du. Hobbesek <em>Leviatan</em> idazten du (1651) gerraren ondoren; Lockek, bere <em>Gobernu zibilari buruzko bi tratatuak</em> (1689) iraultzaren ondoren.</p>",
  "ciencia": "<p>Keplerrek planetak elipseetan biratzen direla aurkitzen du; Harveyk odol-zirkulazioa frogatzen du (1628); mikroskopioak mundu ikusezin bat erakusten du (Hooke, <em>Micrographia</em>, 1665). Newtonek eta Leibnizek bereizita asmatzen dute <strong>kalkulu infinitesimala</strong>, eta Newtonek zeruko eta Lurreko fisika grabitate-lege bakar batean batzen ditu (1687).</p>\n<p>Irudi nagusia <strong>mekanizismoa</strong> da: mundua erloju handi bat bezala dabil, kontaktuz mugitzen diren piezekin lege matematikoen arabera.</p>",
  "pensamiento": "<ul>\n<li><strong>Metodoa eta ziurtasuna:</strong> zer dagoen jakin aurretik, nola ezagut dezakegun jakin behar da.</li>\n<li><strong>Arrazionalismoa:</strong> Descartesek, Spinozak, Malebranchek eta Leibnizek arrazoiak berez ezagutzen dituen ideietan konfiantza dute.</li>\n<li><strong>Enpirismoa:</strong> Lockek eta Berkeleyk ezagutza guztia esperientziatik datorrela sostengatzen dute; Humek muturrera eramango du hurrengo mendean.</li>\n<li><strong>Substantzia:</strong> zenbat daude? Bi Descartesentzat (gogoa eta materia), bat Spinozarentzat, monada infinituak Leibnizentzat, materia bakarrik Hobbesentzat.</li>\n<li><strong>Gizarte-kontratua eta tolerantzia:</strong> Hobbesek eta Lockek boterea itun batean oinarritzen dute; Spinozak (1670) eta Lockek (1689) pentsamendu-askatasuna eta erlijio-tolerantzia defendatzen dituzte.</li>\n</ul>",
  "rupturas": "<p>Newton eta Locke hurrengo belaunaldiaren eredu bihurtzen dira: Voltairek Frantzian ezagutarazten ditu bere <em>Gutun filosofikoak</em> lanean (1734). XVII. mendeak batez ere naturari aplikatu zion arrazoiarekiko konfiantza Ilustrazioak gizarteara, politikara eta erlijiora zabalduko du.</p>",
  "trampa": "<p>«Arrazionalistak eta enpiristak elkarren aurkako bi talde ziren.» Etiketa historialariek ipini zuten geroago. Denek elkar irakurtzen eta erantzuten zuten: Lockek Descartesekin eztabaidatzen du, eta Leibnizek liburu oso bat eskaini zion Lockeri erantzuteko (<em>Giza ulermenari buruzko saiakera berriak</em>). Eta ia guztiek matematikan eta fisika berrian konfiantza partekatzen zuten.</p>"
 },
 "ilu": {
  "anos": "XVII. mendearen amaieratik (1680 inguruan) 1800era arte, gutxi gorabehera.",
  "abre": "<p>Iraultza zientifikoa gailurrera iristen da Newtonen <em>Natur filosofiaren printzipio matematikoak</em> lanarekin (1687): unibertsoak arrazoiak aurki ditzakeen legeak betetzen ditu. Hurrengo urtean, Ingalaterrako Iraultza Loriatsuak (1688-1689) erregea Parlamentuaren eskubide-aitorpen baten mende jartzen du. Arrazoia eta askatasun politikoa dira garaiak urrutien eramango dituen bi ideiak.</p>",
  "social": "<p><strong>Burgesia</strong> bat hazten da, merkatariek, medikuek, abokatuek eta funtzionarioek osatua, irakurtzen, eztabaidatzen eta eragin nahi duena. Gortetik eta Elizatik kanpoko elkarrizketa-guneak sortzen dira: <strong>kafetegiak</strong>, akademiak, masoien loxak eta <strong>salonak</strong>, horietako asko emakumeek zuzenduak, Madame Geoffrinena Parisen bezala. Egunkariak eta liburu merkeak ugaltzen dira, eta zerbait berria agertzen da: <strong>iritzi publikoa</strong>.</p>\n<p>Baina Ilustrazioa gutxiengoen kontua izan zen: biztanleriaren gehiengoa nekazaria zen eta ez zekien irakurtzen. Eta Europako portuen aberastasuna, neurri handi batean, pertsona esklabo bihurtuen Atlantikoko merkataritzaren menpe zegoen.</p>",
  "politico": "<p>Europa ia osoa <strong>monarkia absolutuetan</strong> bizi da. Errege batzuek erreforma ilustratuak hartzen dituzte botererik utzi gabe (<strong>despotismo ilustratua</strong> deitzen dena: Federiko II.a Prusiakoa, Katalina II.a Errusiakoa, Karlos III.a Espainian). Zentsurak aktibo jarraitzen du: <em>Entziklopedia</em> Frantzian debekatu zuten 1759an eta ezkutuan argitaratzen jarraitu zuen.</p>\n<p>Mendearen amaieran, bi iraultzak ideiak politikara eramaten dituzte: <strong>Estatu Batuen independentzia</strong> (1776), bere eskubide-aitorpenarekin, eta <strong>Frantziako Iraultza</strong> (1789), <em>Gizonaren eta herritarraren eskubideen aitorpena</em>rekin.</p>",
  "ciencia": "<p>Newton jakintza guztiaren eredu bihurtzen da: behatu, neurtu eta legeak bilatu. Linneok izaki bizidunak sailkatzen ditu (<em>Naturaren sistema</em>, 1735); Lavoisierrek kimika modernoa sortzen du (<em>Kimikaren oinarrizko tratatua</em>, 1789); Jennerrek lehen txertoa probatzen du, baztangaren aurkakoa (1796). Britainia Handian, Watten lurrun-makinak (1769an patentatua) <strong>Industria Iraultza</strong> irekitzen du.</p>\n<p>Diderot eta d'Alembert-en <em>Entziklopediak</em> (1751-1772) jakintza guztia bildu nahi du, baita lanbideena ere, tailer eta makinen laminekin: ezagutza teknikoa filosofiaren duin bihurtzen da.</p>",
  "pensamiento": "<p>Ideia nagusia Kantek laburbildu zuen 1784an: Ilustrazioa gizakiak berak errua duen adin-txikitasunetik ateratzea da; bere lema, <em>sapere aude</em>, «ausartu zaitez zure adimena erabiltzen!» (<em>Zer da Ilustrazioa?</em>). Hortik datoz bere ezaugarri nagusiak:</p>\n<ul>\n<li><strong>Arrazoi kritikoa:</strong> ez da ezer onartzen tradizioagatik edo autoritateagatik aztertu gabe, ezta arrazoia bera ere (Hume, Kant).</li>\n<li><strong>Aurrerapena:</strong> jakintzak eta hezkuntzak giza bizitza hobetu dezakete (Rousseau, <em>Emile</em>, 1762).</li>\n<li>Erlijio-<strong>tolerantzia</strong> eta sineskeriaren kritika (Voltaire, <em>Tolerantziari buruzko tratatua</em>, 1763). Ilustratu askok deistak dira: Jainko sortzaile batean sinesten dute, baina ez agerpeneko erlijioetan.</li>\n<li><strong>Eskubideak eta botereen banaketa</strong> absolutismoaren aurrean (Montesquieu, <em>Legeen izpiritua</em>, 1748; Rousseau, <em>Gizarte-kontratua</em>, 1762).</li>\n<li><strong>Zoriontasuna eta erabilgarritasuna:</strong> morala sentimenduan oinarrituta pentsatzen da (Hume) edo ondorioetatik (Bentham), eta ekonomia jakintza propio gisa (Adam Smith, <em>Nazioen aberastasuna</em>, 1776).</li>\n<li>Emakumeen <strong>berdintasunaren</strong> aldeko lehen ahotsak: Olympe de Gouges (1791) eta Mary Wollstonecraft (1792).</li>\n</ul>",
  "rupturas": "<p>Ilustrazioa ez da bat-batean amaitzen. Alemanian, Hamannek eta Herderrek sentimendua, hizkuntza eta herri bakoitzaren historia ahazten dituela leporatzen diote, eta <strong>Erromantizismoak</strong> kritika hori jasotzen du. Frantziako Iraultzaren Izuak (1793-1794) galdetzera eramaten du arrazoiak gizarte osoa berregin dezakeen. Kantek garaia ixten du eta aldi berean aztertzen du: haren <em>Kritikek</em> arrazoiaren mugak markatzen dituzte.</p>\n<p>Beste ildo batzuk XIX. mendean jarraitzen dute: Bentham eta Millen <strong>utilitarismoa</strong> eta <strong>liberalismoa</strong> (horregatik doaz «Ospetsuak» atalean garai honetan), eta aurrerapenarekiko fedea, Hegelek eta Marxek jasotzen dutena. XX. mendean, Adornok eta Horkheimerrek (<em>Ilustrazioaren dialektika</em>, 1944) galdetzen diote beren buruari zergatik ez zuen arrazoi ilustratuak barbarie ekidin.</p>",
  "trampa": "<p>«Ilustrazioa frantsesa izan zen.» Paris izan zen bere hiriburu ikusgarriena, baina eskoziar Ilustrazioa ere egon zen (Hume, Smith), alemana (Kant, Lessing, Mendelssohn), espainiarra (Feijoo, Jovellanos) eta amerikarra (Franklin, Jefferson). Eta «ilustratu» ez da «ateo» esan nahi: Holbach ateoa zen, baina Voltaire deista zen eta Kantek sinesmen arrazional bat defendatzen zuen.</p>"
 },
 "con": {
  "nombre": "Aro Garaikidea I: XIX. mendea",
  "block": "con",
  "nacidos": [
   1700,
   1849
  ],
  "temasHF": [
   21
  ],
  "anos": "XVIII. mendearen amaieratik Lehen Mundu Gerrara arte (1800etik 1914ra, gutxi gorabehera).",
  "abre": "<p>Frantziako Iraultzak eta Napoleonen gerrek Europako mapa politikoa aldatzen dute, eta <strong>Industria Iraultzak</strong> bizitzeko eta lan egiteko modua aldatzen du. Filosofian, Kantek arrazoiaren mugei buruzko galdera irekita utzi du, eta idealismo alemanak gainditzen saiatzen da: Hegelek <em>Espirituaren fenomenologia</em> argitaratzen du 1807an.</p>",
  "social": "<p>Fabrikek milioika pertsona erakartzen dituzte landatik hirietara. <strong>Proletalgoa</strong> sortzen da, lanaldi luzeegiekin eta haur-lanarekin, Dickensen eleberriek deskribatzen duten bezala, eta harekin batera langile-mugimendua, sindikatuak eta sozialismoak: utopikoak deritzenak (Owen, Fourier, Saint-Simon) eta Marx eta Engelsena (<em>Manifestu komunista</em>, 1848). Burgesia klase agintari bihurtzen da, eta eskola eta prentsa biztanleriaren geruza gero eta zabalagoetara iristen dira.</p>",
  "politico": "<p>Iraultza liberalen mendea da (1830, 1848), konstituzioena eta <strong>nazionalismoena</strong>: Italia 1861ean bateratzen da eta Alemania 1871n. Europako potentziek Afrika eta Asiaren zati handi bat banatzen dute <strong>inperio kolonialetan</strong> (Berlingo Konferentzia, 1884-1885). Esklabutza pixkanaka abolitzen da: Inperio britainiarrean 1833an, Estatu Batuetan 1865ean gerra zibil baten ondoren, Espainiar Kuban 1886an.</p>",
  "ciencia": "<p>Darwinek espezieen eboluzioa hautespen naturalaren bidez azaltzen du (<em>Espezieen jatorria</em>, 1859) eta Mendelek herentziaren legeak aurkitzen ditu (1866). Faradayk eta Maxwellek elektrizitatea eta magnetismoa bateratzen dituzte; Pasteurrek mikrobioek gaixotasunetan duten zeregina frogatzen du. Trenbideak, telegrafoak eta elektrizitateak eguneroko bizitza eraldatzen dute. Boolek eta Fregek logika matematikaren adar bihurtzen hasten dira.</p>",
  "pensamiento": "<ul>\n<li><strong>Idealismoa eta Erromantizismoa:</strong> Fichtek, Schellingek eta Hegelek errealitatea izpirituaren garapen gisa pentsatzen dute; Novalisek, Schlegelek eta Hölderlinek sentimendua, artea eta herri bakoitzaren historia aldarrikatzen dituzte.</li>\n<li><strong>Positibismoa:</strong> Comtek dioenez, jakintza zientzia positiboan gailentzen da, behatzeko moduko gertaeretan oinarritua.</li>\n<li><strong>Utilitarismoa eta liberalismoa:</strong> Millek banakoaren askatasuna defendatzen du Estatuaren aurrean eta gehiengoaren presioaren aurrean (<em>Askatasunari buruz</em>, 1859).</li>\n<li><strong>Sozialismoa eta anarkismoa:</strong> Marxek, Proudhonek eta Kropotkinek jabetza eta kapitalismoa kritikatzen dituzte jarrera desberdinetatik.</li>\n<li><strong>Susmoa:</strong> Marxek eta Nietzschek ideien atzean interes ekonomikoak edo boterearen nahimena bilatzen dituzte.</li>\n</ul>",
  "rupturas": "<p>XIX. mendeak <strong>aurrerapenean</strong> konfiantza du: erakusketa unibertsalek gero eta makina txundigarriagoak erakusten dituzte. Baina barruan arrakalak hazten dira: Nietzschek «Jainkoaren heriotza» iragartzen du (1882), Freudek arrazoiak kontrolatzen ez duen inkontziente bat arakatzen du (<em>Ametsen interpretazioa</em>, 1900) eta fisika klasikoa kulunka hasten da (Einstein, 1905). Lehen Mundu Gerrak (1914) behin betiko hausten du konfiantza hori.</p>",
  "trampa": "<p>«Garaikidea gaurkoa esan nahi du.» Historian, Aro Garaikidea XVIII. mendearen amaieran hasten da: Hegel eta Marx filosofo «garaikideak» dira, duela bi mende bizi izan baziren ere. Horregatik web honetan aroa bi fitxatan banatzen da: XIX. mendea eta XX. eta XXI. mendeak.</p>"
 },
 "con2": {
  "nombre": "Aro Garaikidea II: XX. eta XXI. mendeak",
  "block": "con",
  "nacidos": [
   1850,
   2100
  ],
  "temasHF": [
   22,
   23,
   24,
   25,
   26,
   27
  ],
  "anos": "Lehen Mundu Gerratik (1914) gaur egunera arte.",
  "abre": "<p><strong>Lehen Mundu Gerrak</strong> (1914-1918), milioika hildako trintxeretan eta serieka fabrikatutako armekin, XIX. mendeak aurrerapenean zuen konfiantza hausten du. 1917an, Errusiako Iraultzak klaserik gabeko gizarte bat agintzen du. Mendea hasten da zer huts egin duen galdetzen, aurreratuena zela uste zen zibilizazioan.</p>",
  "social": "<p><strong>Masen gizartea</strong> iristen da: hiri handiak, kontsumoa, zinema, irratia eta telebista. Emakumeek botoa lortzen dute (Espainian, 1931n) eta eskola ia guztiengana iristen da. Mendearen bigarren erdian <strong>Ongizate Estatua</strong> hedatzen da Europan, osasun eta pentsio publikoekin.</p>\n<p>Gaur egun mundu <strong>globalizatu</strong> batean bizi gara, interneten bidez konektatua, desberdintasun izugarriekin, migrazio handiekin eta aurrerapena birpentsatzera behartzen gaituen krisi ekologiko batekin.</p>",
  "politico": "<p>Bi mundu-gerren artean <strong>totalitarismoak</strong> sortzen dira (faxismoa, nazismoa, estalinismoa). Bigarren Mundu Gerra (1939-1945) Holokaustoarekin eta Hiroshimako eta Nagasakiko bonba atomikoekin amaitzen da. Geroago NBE eta Giza Eskubideen Aldarrikapen Unibertsala sortzen dira (1948), Gerra Hotza hasten da eta Asia eta Afrika deskolonizatzen dira.</p>\n<p>Espainian, diktadura frankistak (1939-1975) pentsalari asko erbestera bidaltzen ditu, María Zambrano bezala. Berlingo harresiaren erorketak (1989) Gerra Hotza ixten du; XXI. mendeak 2008ko finantza-krisia, covid-19 pandemia (2020) eta gerra berriak dakartza.</p>",
  "ciencia": "<p>Einsteinek (erlatibitatea) eta mekanika kuantikoak espazioaren, denboraren eta materiaren ideia aldatzen dute. 1953an ADNren egitura deskribatzen da, Rosalind Franklinen datuekin. Turingek (1936) eta Shannonek (1948) informatikaren oinarriak jartzen dituzte. Energia nuklearrak, Ilargirako bidaiak (1969), internetek eta adimen artifizialak botere tekniko izugarria erakusten dute, eta horrek haren mugez galdetzera behartzen gaitu.</p>",
  "pensamiento": "<ul>\n<li><strong>Psikoanalisia:</strong> Freudek erakusten du ez garela gure gogoaren jabe osoak.</li>\n<li><strong>Existentzia eta fenomenologia:</strong> Heideggerrek, Sartrek, Beauvoirrek eta Camusek existentzia konkretutik, askatasunetik eta larritasunetik abiatzen dira.</li>\n<li><strong>Hizkuntzaren bira:</strong> Wittgensteinek eta filosofia analitikoak hizkuntza aztertzen dute; Popperrek eta Kuhnek, zientzia.</li>\n<li><strong>Teoria kritikoa:</strong> Frankfurteko Eskolak (Horkheimer, Adorno, Habermas) masen gizartea aztertzen du.</li>\n<li><strong>Filosofia Espainian:</strong> Unamuno, Ortega eta Zambrano; euskaraz, Txillardegi eta Azurmendi.</li>\n<li><strong>Gaurko eztabaidak:</strong> feminismoa (Beauvoir, Butler), posmodernitatea (Lyotard, Foucault, Derrida), justizia (Rawls), ekologia (Yayo Herrero), teknologia eta gogoa (Han, Bostrom, Chalmers).</li>\n</ul>",
  "rupturas": "<p>Amaitu ez den aro bat da, barne-mozketa batzuekin. Auschwitzek eta Hiroshimak zer egin duen arrazoiak galdetzera behartzen dute (Adorno, Arendt); 1979an, Lyotardek «kontakizun handien» amaiera iragartzen du. Gaur irekita dauden galderek, adimen artifizialak, klima-krisiak edo desinformazioak adibidez, beharbada oraindik izendatzen jakin ez dugun beste aro bat irekitzen ari dira.</p>",
  "trampa": "<p>«Gaurko filosofian dena balio du.» Korronte asko egoteak ez du esan nahi edozein iritzik balio duenik: bakoitzak arrazoiekin eztabaidatzen du besteekin. Eta «posmodernoa» ez da irain bat, ezta «oso modernoa» esan nahi ere: kontakizun handien amaierari buruzko tesi zehatz bat da, kritikariak ere dituena, Habermas bezala.</p>"
 }
};
